const {app,BrowserWindow,dialog}=require('electron'),fs=require('node:fs/promises'),path=require('node:path');
app.disableHardwareAcceleration();app.setPath('userData',path.resolve('test-output/batch-ui-session'));
dialog.showOpenDialog=async(_window,options)=>({canceled:false,filePaths:options.properties.includes('openDirectory')?[path.resolve(options.title?'test-output/batch-export':'test-output/batch-input')]:[path.resolve('test-output/signature.png')]});
require('../electron/main.cjs');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await app.whenReady();const win=BrowserWindow.getAllWindows()[0];await new Promise(r=>win.webContents.once('did-finish-load',r));await wait(700);
 const click=async text=>win.webContents.executeJavaScript(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes(${JSON.stringify(text)})).click()`);
 const until=async expression=>{for(let i=0;i<120;i++){await wait(500);const e=await win.webContents.executeJavaScript(`document.querySelector('.message.error')?.textContent`);if(e)throw new Error(e);if(await win.webContents.executeJavaScript(expression))return;}throw new Error('Timeout UI: '+expression);};
 if(process.argv.includes('--restore-check')){const restored=await win.webContents.executeJavaScript(`({photos:document.querySelectorAll('.batch-item').length,explanations:Array.from(document.querySelectorAll('.explanation-grid p')).map(e=>e.textContent)})`);if(restored.photos!==2||restored.explanations.length!==2)throw new Error('Session non restaurée');await fs.writeFile('test-output/batch-restore-report.json',JSON.stringify(restored,null,2));app.quit();return;}
 await win.webContents.executeJavaScript(`document.querySelectorAll('.file-card')[1].click()`);await wait(500);await click('Un dossier');await until(`document.querySelectorAll('.batch-item').length===2`);
 await win.webContents.executeJavaScript(`document.querySelector('.batch-panel .checkbox input').click()`);await click('Analyser les photos restantes');await until(`Array.from(document.querySelectorAll('.batch-item small')).every(e=>e.textContent==='Validée')`);
 for(let i=0;i<2;i++){await win.webContents.executeJavaScript(`document.querySelectorAll('.batch-item')[${i}].click()`);await wait(600);const details=await win.webContents.executeJavaScript(`Array.from(document.querySelectorAll('.explanation-grid article')).map(e=>e.textContent)`);if(details.length!==2||details.some(s=>s.includes('ancienne suggestion')))throw new Error('Justifications manquantes');}
 await click('Exporter les photos validées');await until(`Array.from(document.querySelectorAll('.batch-item small')).every(e=>e.textContent==='Exportée')`);
 await fs.writeFile('test-output/batch-ui.png',(await win.webContents.capturePage()).toPNG());const report=await win.webContents.executeJavaScript(`({explanations:Array.from(document.querySelectorAll('.explanation-grid article')).map(e=>e.textContent),statuses:Array.from(document.querySelectorAll('.batch-item small')).map(e=>e.textContent),status:document.querySelector('[role=status]')?.textContent})`);await fs.writeFile('test-output/batch-ui-report.json',JSON.stringify(report,null,2));app.quit();
})().catch(async error=>{await fs.writeFile('test-output/batch-ui-error.txt',error.stack);app.exit(1);});
