const {app,BrowserWindow,dialog}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
app.disableHardwareAcceleration();app.setPath('userData',path.resolve('test-output/gallery-ui-session-'+process.pid));
dialog.showOpenDialog=async(_window,options)=>({canceled:false,filePaths:[path.resolve(options.title==='Choisir le dossier de sortie'?'test-output':options.properties.includes('openDirectory')?'test-output/batch-input':'test-output/signature.png')]});
require('../electron/main.cjs');
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 await app.whenReady();const win=BrowserWindow.getAllWindows()[0];await new Promise(resolve=>win.webContents.once('did-finish-load',resolve));await wait(800);
 const js=source=>win.webContents.executeJavaScript(source);
 await js(`Array.from(document.querySelectorAll('.workspace button')).find(b=>b.textContent==='Un dossier').click()`);await wait(900);
 assert.equal(await js(`document.querySelectorAll('.workspace .batch-item').length`),2);
 assert.equal(await js(`document.querySelectorAll('.workspace .photo-thumbnail img').length`),2);
 assert.equal(await js(`document.querySelector('.workspace .photo-counter').textContent`),'1 / 2');
 await js(`document.querySelector('.workspace .photo-next').click()`);await wait(500);
 assert.equal(await js(`document.querySelector('.workspace .photo-counter').textContent`),'2 / 2');
 assert.equal(await js(`document.querySelector('.workspace .photo-next').disabled`),true);
 await js(`document.querySelector('.workspace .file-card:not(.selection-pick)').click()`);await wait(500);
 await js(`document.querySelector('.invert-mark').click()`);await wait(600);
 assert.equal(await js(`document.querySelector('.overlay').style.filter`),'invert(1)');
 const changed=JSON.parse(await fs.readFile(path.join(app.getPath('userData'),'session.json'),'utf8'));assert.equal(changed.batch.items[1].value.inverted,true);
 await js(`document.querySelectorAll('.module-tabs button')[1].click()`);await wait(300);
 assert.equal(await js(`document.querySelector('.review-photo .photo-counter').textContent`),'2 / 2');
 await js(`document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}))`);await wait(600);
 assert.equal(await js(`document.querySelector('.review-photo .photo-counter').textContent`),'1 / 2');
 await js(`document.querySelectorAll('.module-tabs button')[0].click()`);await wait(250);
 assert.equal(await js(`document.querySelector('.overlay').style.filter`),'none');
 await js(`document.querySelector('.workspace .photo-next').click()`);await wait(600);
 assert.equal(await js(`document.querySelector('.overlay').style.filter`),'invert(1)');
 await js(`document.querySelector('.workspace .model-row input').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}))`);await wait(100);
 assert.equal(await js(`document.querySelector('.workspace .photo-counter').textContent`),'2 / 2');
 const result=await js(`window.studio.export({x:.1,y:.1,width:.2,opacity:1,inverted:true})`);assert.equal(result.ok,true);
 await fs.writeFile('test-output/gallery-ui-report.json',JSON.stringify({ok:true,thumbnails:2,navigation:true,keyboard:true,sharedSelection:true,inversionPerPhoto:true,restoration:true,export:result.data},null,2));app.quit();
})().catch(error=>{console.error(error);app.exit(1);});
