import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import './theme.css';
import './batch.css';
import Review from './Review.jsx';
import Selection from './Selection.jsx';
import {PhotoList,PhotoNavigation} from './Gallery.jsx';
function Icon({name}){
  const paths={photo:<><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 6-6 4 4 3-3 5 5"/></>,signature:<><path d="M4 17c8-16 11-13 5-5-4 6-1 8 3 3 4-5 2 3 5 1l3-2M3 21h18"/></>,refresh:<><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 6a8 8 0 0 1 13 3M18 18A8 8 0 0 1 5 15"/></>,spark:<><path d="m12 3 2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3Z"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></>,arrow:<><path d="M6 18 18 6M6 6h12v12"/></>,plus:<path d="M12 5v14M5 12h14"/>};
  return <svg className="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.photo}</svg>;
}
const defaultPlacement={x:0.76,y:0.88,width:0.2,opacity:0.8,reason:''};
const statusLabels={pending:'À analyser',analyzing:'Analyse…',suggested:'À valider',approved:'Validée',exported:'Exportée',error:'Erreur analyse','export-error':'Erreur export'};
function Explanation({value,photo,mark}){
  if(!value.reason)return <div className="result"><span className="spark"><Icon name="spark"/></span><div><strong>Votre signature, votre décision</strong><p>Demandez une suggestion pour obtenir une justification de la position et de la taille.</p></div></div>;
  const p=value.proposed||value,w=Math.max(1,Math.round(p.width*photo.width)),h=Math.max(1,Math.round(w*mark.height/mark.width)),x=Math.round(p.x*photo.width),y=Math.round(p.y*photo.height);
  const cx=(x+w/2)/photo.width,cy=(y+h/2)/photo.height;
  const region=`${cy<.33?'En haut':cy>.67?'En bas':'Au centre'}${cx<.33?' à gauche':cx>.67?' à droite':''}`;
  const modified=value.proposed&&['x','y','width','opacity','inverted'].some(k=>p[k]!==value[k]);
  return <div className="explanations"><div className="explanation-title"><Icon name="spark"/><strong>{value.manual?'Réglages copiés manuellement':'Proposition du modèle pour cette photo'}</strong></div><div className="explanation-grid"><article><h3>Position · {region}</h3><small>Coin supérieur gauche : {x}, {y} px</small><p>{value.position_reason||value.reason}</p></article><article><h3>Taille · {(p.width*100).toFixed(1)} % de la largeur</h3><small>{w} × {h} px · Opacité {Math.round(p.opacity*100)} %</small><p>{value.size_reason||'Cette ancienne suggestion ne contient pas de justification de taille. Relancez l’analyse pour la compléter.'}</p></article><article><h3>Couleur · {(p.inverted??!!mark.inverted)?'inversée':'originale'}</h3><p>{value.color_reason||'Relancez une suggestion pour obtenir la justification du contraste.'}</p></article></div>{modified&&<p className="manual-note">Vous avez modifié les réglages. Ces explications décrivent la proposition initiale du modèle ; l’aperçu et l’export utilisent vos réglages actuels.</p>}</div>;
}
async function api(name,...args){const result=await window.studio[name](...args);if(!result.ok)throw new Error(result.error);return result.data;}
function fit(value,photo,mark){
  if(!photo||!mark)return value;
  const maxWidth=Math.min(1,photo.height*mark.width/(photo.width*mark.height));
  const width=Math.max(1/photo.width,Math.min(value.width,maxWidth));
  const h=width*photo.width*mark.height/mark.width/photo.height;
  return {...value,width,x:Math.max(0,Math.min(value.x,1-width)),y:Math.max(0,Math.min(value.y,1-h)),opacity:Math.max(0,Math.min(1,value.opacity))};
}
function App(){
  const [module,setModule]=useState('watermark'),[reviewInitial,setReviewInitial]=useState(null);
  const [photo,setPhoto]=useState(null),[mark,setMark]=useState(null),[value,setValue]=useState(defaultPlacement);
  const [base,setBase]=useState('http://localhost:11434'),[model,setModel]=useState('qwen3-vl:8b-instruct'),[models,setModels]=useState([]),[mode,setMode]=useState('discret');
  const [comment,setComment]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[original,setOriginal]=useState(false),[ready,setReady]=useState(false),[exported,setExported]=useState('');
  const stage=useRef(null),drag=useRef(null);
  const [batch,setBatch]=useState({items:[],activeId:null,running:false,progress:null}),[recursive,setRecursive]=useState(true),[autoApprove,setAutoApprove]=useState(false);
  const active=batch.items.find(item=>item.id===batch.activeId),hasBatch=batch.items.length>0;
  const valid=photo&&mark;
  const effectiveInverted=value.inverted??!!mark?.inverted,markFilter=effectiveInverted!==!!mark?.inverted?'invert(1)':'none';
  useEffect(()=>window.studio.onBatch(state=>{setBatch(state);if(state.running){const item=state.items.find(p=>p.id===state.activeId);if(item?.value)setValue(v=>JSON.stringify(v)===JSON.stringify(item.value)?v:item.value);}}),[]);
  useEffect(()=>{if(!ready||!batch.activeId||batch.running||busy||!mark)return;const id=batch.activeId,t=setTimeout(()=>{api('batchUpdate',id,value).catch(e=>setError(e.message));},250);return()=>clearTimeout(t);},[ready,batch.activeId,batch.running,busy,value,mark]);
  useEffect(()=>{api('restore').then(saved=>{if(saved){setReviewInitial(saved.review||null);if(saved.batch)setBatch(saved.batch);setPhoto(saved.photo);setMark(saved.mark);const s=saved.state||{};setBase(s.base||'http://localhost:11434');setModel(s.model||'qwen3-vl:8b-instruct');setMode(s.mode||'discret');setComment(s.comment||'');setValue(fit(saved.batch?.items.find(p=>p.id===saved.batch.activeId)?.value||s.value||defaultPlacement,saved.photo,saved.mark));if(saved.warnings.length)setError('Session : '+saved.warnings.join(' '));else if(saved.photo)setNotice('Session précédente restaurée.');}}).catch(e=>setError(e.message)).finally(()=>setReady(true));},[]);
  useEffect(()=>{if(!ready)return;const t=setTimeout(()=>{api('save',{base,model,mode,comment,value}).catch(e=>setError('Sauvegarde : '+e.message));},350);return()=>clearTimeout(t);},[ready,base,model,mode,comment,value,photo,mark]);
  async function run(label,task){setBusy(label);setError('');setNotice('');try{await task();}catch(e){setError(e.message);}finally{setBusy('');}}
  async function pick(kind){await run('Chargement',async()=>{const image=await api('pick',kind);if(!image)return;const p=kind==='photo'?image:photo,m=kind==='mark'?image:mark;if(kind==='photo'){setPhoto(image);setBatch({items:[],activeId:null,running:false});}else setMark(image);setValue(fit({...defaultPlacement,reason:''},p,m));setComment('');setExported('');});}
  async function importBatch(kind){await run('Import du lot',async()=>{const result=await api('batchImport',kind,recursive);if(!result)return;setBatch(result.batch);setPhoto(result.photo);setValue(result.batch.items[0].value||defaultPlacement);setComment('');setExported('');setNotice(`${result.batch.items.length} photo(s) importée(s). ${result.warnings.join(' ')}`);});}
  async function selectPhoto(id){await run('Chargement',async()=>{if(active&&mark)await api('batchUpdate',active.id,value);const result=await api('batchSelect',id);setBatch(result.batch);setPhoto(result.photo);setValue(result.value||fit(defaultPlacement,result.photo,mark));setComment('');setExported('');});}
  function change(key,n){if(key==='inverted'?typeof n!=='boolean':!Number.isFinite(n))return;setValue(v=>fit({...v,[key]:n},photo,mark));setExported('');}
  async function analyze(){await run('Analyse Ollama',async()=>{const suggestion=await api('suggest',{base,model,mode,comment,current:value});setValue(suggestion);setExported('');setOriginal(false);setNotice('Proposition reçue. Vérifie l’aperçu avant l’export.');});}
  async function invertMark(){if(photo){change('inverted',!(value.inverted??!!mark.inverted));setOriginal(false);setNotice('Couleur modifiée pour cette photo. Relancez une suggestion pour adapter le contraste.');return;}await run('Inversion des couleurs',async()=>{const result=await api('invertMark',value);setMark(result.mark);setBatch(result.batch);setValue(v=>({...v,reason:'',position_reason:'',size_reason:'',color_reason:'',proposed:null,manual:false}));setExported('');setOriginal(false);setNotice('Couleurs du watermark '+(result.mark.inverted?'inversées':'rétablies')+'. Relancez une suggestion pour adapter le placement au contraste.');});}
  const box=valid?{width:Math.max(1,Math.round(value.width*photo.width)),height:Math.max(1,Math.round(Math.max(1,Math.round(value.width*photo.width))*mark.height/mark.width)),left:Math.round(value.x*photo.width),top:Math.round(value.y*photo.height)}:null;
  function startDrag(e){if(busy||original)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={px:e.clientX,py:e.clientY,x:value.x,y:value.y};}
  function moveDrag(e){if(!drag.current)return;const rect=stage.current.getBoundingClientRect();const d=drag.current;setValue(v=>fit({...v,x:d.x+(e.clientX-d.px)/rect.width,y:d.y+(e.clientY-d.py)/rect.height},photo,mark));setExported('');}
  return <main>
    <header><div className="brand"><img className="brand-icon" src="assets/icon.png" alt=""/><div><h1>Watermark <span>Studio</span></h1><p>Votre regard. Votre signature.</p></div></div><nav className="module-tabs" aria-label="Modules"><button disabled={!!busy} className={module==='watermark'?'active':''} aria-pressed={module==='watermark'} onClick={()=>setModule('watermark')}>Watermark</button><button disabled={!!busy} className={module==='review'?'active':''} aria-pressed={module==='review'} onClick={()=>setModule('review')}>Critique photo</button></nav><span className="badge"><i/> ATELIER PHOTO · IA LOCALE · v0.5</span></header>
    <div className="workspace" style={{display:module==='watermark'?'grid':'none'}}><aside>
      <Selection showList={false} photo={photo} batch={batch} busy={busy} pick={pick} importBatch={importBatch} selectPhoto={selectPhoto} recursive={recursive} setRecursive={setRecursive}/>
      <section><div className="section-heading"><span>WM</span><h2>La signature</h2></div>
        <button className="file-card" disabled={!!busy} onClick={()=>pick('mark')}><span className="file-icon"><Icon name="signature"/></span><span><strong>{mark?mark.name:'Choisir le watermark'}</strong><small>{mark?`${mark.width} × ${mark.height} px`:'PNG avec transparence'}</small></span><Icon name="plus"/></button>
        {mark&&<div className="mark-sample"><img src={mark.preview} style={{filter:markFilter}} alt="Votre watermark sur fond transparent"/></div>}
        <button className="secondary full invert-mark" disabled={!mark||!!busy||batch.running} aria-pressed={effectiveInverted} onClick={invertMark}>{effectiveInverted?'Rétablir les couleurs':'Inverser les couleurs'}</button>
        {mark&&<p className="hint">Blanc ↔ noir · Transparence conservée{photo?' · Pour cette photo':''} · L’IA peut aussi proposer l’inversion</p>}
      </section>
      {hasBatch&&<section className="batch-panel"><div className="section-heading"><span>LOT</span><h2>{batch.items.length} photos</h2><small>{batch.items.filter(p=>p.status==='exported').length} exportées</small></div><PhotoList batch={batch} busy={busy} selectPhoto={selectPhoto}/><label className="checkbox"><input type="checkbox" checked={autoApprove} disabled={!!busy} onChange={e=>setAutoApprove(e.target.checked)}/> Valider automatiquement les propositions</label><button className="primary full" disabled={!mark||!!busy||!batch.items.some(p=>['pending','error'].includes(p.status))} onClick={()=>run('Analyse du lot',async()=>{await api('batchUpdate',batch.activeId,value);setBatch(await api('batchAnalyze',{base,model,mode,autoApprove}));setNotice('Analyse du lot terminée. Consultez les justifications photo par photo.');})}>Analyser les photos restantes</button>{batch.progress&&<div className="batch-progress"><progress value={batch.progress.done} max={batch.progress.total||1}/><small>{batch.progress.kind} · {batch.progress.done}/{batch.progress.total} · {batch.progress.name}</small></div>}{['Analyse du lot','Export du lot'].includes(busy)&&<button className="quiet full" onClick={()=>api('cancel')}>Arrêter le traitement</button>}</section>}
      <section><div className="section-heading"><span>02</span><h2>Vision locale</h2></div>
        <label>Serveur Ollama<input value={base} disabled={!!busy} onChange={e=>setBase(e.target.value)}/></label>
        <label>Modèle vision<div className="model-row"><input value={model} disabled={!!busy} list="models" onChange={e=>setModel(e.target.value)}/><button disabled={!!busy} aria-label="Vérifier Ollama et lister les modèles" title="Vérifier Ollama et lister les modèles" onClick={()=>run('Connexion',async()=>{const names=await api('models',base);setModels(names);setNotice(names.length?`${names.length} modèle(s) disponible(s).`:'Aucun modèle installé. Lance : ollama pull qwen3-vl:8b-instruct');})}><Icon name="refresh"/></button></div><datalist id="models">{models.map(m=><option key={m} value={m}/>)}</datalist></label>
        <div className="segmented">{['discret','équilibré','protection'].map(m=><button key={m} disabled={!!busy} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m}</button>)}</div>
        <button className="primary full" disabled={!valid||!!busy} onClick={analyze}><Icon name="spark"/>{busy==='Analyse Ollama'?'Analyse en cours…':'Proposer un placement'}</button>
        {busy==='Analyse Ollama'&&<button className="quiet full" onClick={()=>api('cancel')}>Annuler l’analyse</button>}
        <p className="hint">Les deux images sont analysées par Ollama sur cette machine. Seuls des aperçus réduits lui sont transmis.</p>
      </section>
      <section><div className="section-heading"><span>03</span><h2>Affiner la proposition</h2></div>
        <textarea placeholder="Ex. : plus petit, en bas à gauche, sans couvrir le sujet…" value={comment} disabled={!!busy} onChange={e=>setComment(e.target.value)}/>
        <button className="secondary full" disabled={!valid||!comment.trim()||!!busy} onClick={analyze}>Demander un ajustement</button>
      </section>
    </aside>
    <div className="canvas-column"><div className="canvas-toolbar"><div><h2>Aperçu</h2><span>{photo?'Déplace la signature directement sur la photo':'Commence par choisir tes deux images'}</span></div><button className="secondary" disabled={!valid} onClick={()=>setOriginal(!original)}>{original?'Voir le watermark':'Voir l’original'}</button></div>
      <div className="canvas-shell"><PhotoNavigation batch={batch} busy={busy} selectPhoto={selectPhoto} visible={module==='watermark'}/>{photo?<div ref={stage} className="stage" style={{aspectRatio:`${photo.width}/${photo.height}`}}><img className="photo" src={photo.preview} alt="Photo originale" draggable="false"/>{valid&&!original&&<img className="overlay" src={mark.preview} alt="Watermark déplaçable" draggable="false" onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} style={{left:`${box.left/photo.width*100}%`,top:`${box.top/photo.height*100}%`,width:`${box.width/photo.width*100}%`,height:`${box.height/photo.height*100}%`,opacity:value.opacity,filter:markFilter}}/>}</div>:<div className="empty"><div className="empty-art"><Icon name="photo"/><span className="empty-signature"><Icon name="signature"/></span></div><span className="eyebrow">LA TOUCHE FINALE</span><h3>Votre photo mérite votre signature.</h3><p>Un placement proposé par la vision locale.<br/>Une composition que vous maîtrisez.</p><button className="secondary" disabled={!!busy} onClick={()=>pick('photo')}>Ouvrir une photo JPEG <Icon name="arrow"/></button><small>JPEG + PNG transparent · Original préservé</small></div>}</div>
      {valid?<Explanation value={value} photo={photo} mark={mark}/>:<div className="result"><p>Importez vos images pour commencer.</p></div>}
      <section className="adjustments"><div className="section-heading"><span>04</span><h2>Réglages précis</h2><small>Ratio verrouillé</small></div><div className="controls">{[['x','Position X'],['y','Position Y'],['width','Largeur'],['opacity','Opacité']].map(([key,title])=><label key={key}>{title}<div className="numeric"><input type="number" min={key==='width'?0.1:0} max="100" step="0.1" disabled={!valid||!!busy} value={Number((value[key]*100).toFixed(2))} onChange={e=>change(key,Number(e.target.value)/100)}/><span>%</span></div><input type="range" min={key==='width'?0.1:0} max="100" step="0.1" disabled={!valid||!!busy} value={value[key]*100} onChange={e=>change(key,Number(e.target.value)/100)}/></label>)}</div>{box&&<p className="hint">Placement appliqué : {box.left}, {box.top} px · watermark {box.width} × {box.height} px · photo {photo.width} × {photo.height} px</p>}</section>
      {error&&<div role="alert" className="message error">{error}</div>}{notice&&<div role="status" className="message">{notice}</div>}
      {active?.error&&<div className="message error">{active.relative} : {active.error}</div>}
      {hasBatch&&<div className="batch-validation"><span>{statusLabels[active?.status]} · {batch.items.filter(p=>p.status==='approved').length} validée(s) à exporter</span><button className="secondary" disabled={!valid||!!busy} onClick={()=>run('Validation',async()=>setBatch(await api('batchUpdate',batch.activeId,value,true)))}>Valider cette photo</button><button className="quiet" disabled={!valid||!!busy} onClick={()=>run('Copie des réglages',async()=>setBatch(await api('batchApply',value)))}>Copier ces réglages au lot</button></div>}
      <footer><div><strong><Icon name="lock"/> Original intact · Export JPEG</strong><p>Mêmes dimensions, métadonnées conservées. JPEG réencodé à qualité 100.</p></div>{hasBatch?<button className="primary" disabled={!valid||!!busy||!batch.items.some(p=>['approved','export-error'].includes(p.status))} onClick={()=>run('Export du lot',async()=>{await api('batchUpdate',batch.activeId,value);const result=await api('batchExport');if(result){setBatch(result);setNotice(`${result.items.filter(p=>p.status==='exported').length} photo(s) exportée(s). ${result.items.filter(p=>p.status==='export-error').length} erreur(s).`);}})}>Exporter les photos validées <Icon name="arrow"/></button>:<button className="primary" disabled={!valid||!!busy} onClick={()=>run('Export',async()=>{const file=await api('export',value);if(file){setExported(file);setNotice('Export réussi : '+file);}})}>{busy==='Export'?'Export en cours…':'Exporter la photo'}<Icon name="arrow"/></button>}</footer>{exported&&<button className="quiet reveal" onClick={()=>api('reveal')}>Afficher le fichier exporté</button>}
    </div></div>
    {ready&&<Review initial={reviewInitial} base={base} model={model} setBase={setBase} setModel={setModel} currentPhoto={photo} batch={batch} setBatch={setBatch} selectionProps={{photo,batch,busy,pick,importBatch,selectPhoto,recursive,setRecursive}} busy={busy} setBusy={setBusy} visible={module==='review'} sharedError={error}/>}
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
