import React,{useState,useEffect} from 'react';
import {criteria,defaultWeights,overall} from '../lib/scoring.cjs';
import './review.css';
import Selection from './Selection.jsx';
async function api(name,...args){const r=await window.studio[name](...args);if(!r.ok)throw new Error(r.error);return r.data;}
export default function Review({initial,base,model,setBase,setModel,currentPhoto,batch,setBatch,selectionProps,busy,setBusy,visible,sharedError}){
 const [photo,setPhoto]=useState(initial?.photo||null),[assessment,setAssessment]=useState(initial?.assessment||null),[weights,setWeights]=useState(initial?.weights||{...defaultWeights}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[models,setModels]=useState([]);
 const totalWeight=Object.values(weights).reduce((a,b)=>a+b,0),score=overall(assessment,weights);
 const active=batch.items.find(item=>item.id===batch.activeId);
 useEffect(()=>{let live=true;setPhoto(currentPhoto);setAssessment(null);setError('');setNotice('');api('reviewCurrent').then(data=>{if(live){setPhoto(data.photo);setAssessment(data.assessment);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[currentPhoto?.selectionKey,active?.assessment?.analyzedAt,active?.reviewError]);
 useEffect(()=>{const timer=setTimeout(()=>api('reviewWeights',weights).catch(e=>setError('Sauvegarde : '+e.message)),300);return()=>clearTimeout(timer);},[weights]);
 async function run(label,task){setBusy(label);setError('');setNotice('');try{await task();}catch(e){setError(e.message);}finally{setBusy('');}}
 async function pick(){await selectionProps.pick('photo');}
 function changeWeight(key,value){if(Number.isFinite(value)&&value>=0&&value<=10)setWeights(w=>({...w,[key]:value}));}
 return <div className="review-workspace" style={{display:visible?'grid':'none'}}>
  <aside className="review-sidebar"><Selection {...selectionProps} reviewMode/>
  <section><div className="section-heading"><span>02</span><h2>Vision locale</h2></div><label>Serveur Ollama<input value={base} disabled={!!busy} onChange={e=>setBase(e.target.value)}/></label><label>Modèle partagé avec Watermark<div className="model-row"><input list="review-models" value={model} disabled={!!busy} onChange={e=>setModel(e.target.value)}/><button disabled={!!busy} aria-label="Lister les modèles pour la critique" onClick={()=>run('Connexion critique',async()=>{setModels(await api('models',base));setNotice('Connexion à Ollama vérifiée.');})}>↻</button></div><datalist id="review-models">{models.map(name=><option key={name} value={name}/>)}</datalist></label><button className="primary full review-analyze" disabled={!photo||!!busy} onClick={()=>run('Critique en cours',async()=>{setAssessment(await api('reviewAnalyze',{base,model}));setNotice('Critique terminée. Ajustez les poids pour recalculer la note globale.');})}>{busy==='Critique en cours'?'Évaluation en cours…':assessment?'Réévaluer la photo':'Évaluer la photo'}</button>{busy==='Critique en cours'&&<button className="quiet full" onClick={()=>api('cancel')}>Annuler l’évaluation</button>}</section>
  {batch.items.length>0&&<section><button className="primary full review-batch" disabled={!!busy} onClick={()=>run('Critique du lot',async()=>{setBatch(await api('reviewAnalyzeBatch',{base,model}));const current=await api('reviewCurrent');setAssessment(current.assessment);setNotice('Critiques du lot terminées. Consultez chaque photo de la sélection.');})}>Évaluer les photos restantes</button>{batch.progress?.kind==='critique'&&<div className="batch-progress"><progress value={batch.progress.done} max={batch.progress.total||1}/><small>{batch.progress.done}/{batch.progress.total} · {batch.progress.name}</small></div>}{busy==='Critique du lot'&&<button className="quiet full" onClick={()=>api('cancel')}>Arrêter les critiques</button>}</section>}
  <section className="weights-panel"><div className="section-heading"><span>03</span><h2>Pondérations</h2><button className="quiet" onClick={()=>setWeights({...defaultWeights})}>Égaliser</button></div>{criteria.map(({key,label})=><label className="weight-control" key={key}><div><span>{label}</span><small>{totalWeight?Math.round(weights[key]/totalWeight*100):0} %</small></div><div className="weight-row"><input type="range" min="0" max="10" step="0.5" value={weights[key]} onChange={e=>changeWeight(key,Number(e.target.value))}/><input type="number" min="0" max="10" step="0.5" value={weights[key]} aria-label={`Poids ${label}`} onChange={e=>changeWeight(key,Number(e.target.value))}/></div></label>)}<p className="hint">Poids 0 : critère exclu de la moyenne. Le total est normalisé automatiquement. Changer les poids ne relance pas l’IA.</p>{totalWeight===0&&<div className="message error">Attribuez un poids positif à au moins un critère pour obtenir une note globale.</div>}</section>
  </aside>
  <div className="review-content"><div className="review-heading"><div><span className="eyebrow">LE REGARD CRITIQUE</span><h2>Ce que raconte votre photo.</h2><p>Six critères justifiés. Une note globale selon vos priorités.</p></div><button className="secondary" disabled={!assessment||!!busy} onClick={()=>run('Export critique',async()=>{const file=await api('reviewExport',weights);if(file)setNotice('Rapport enregistré : '+file);})}>Exporter le rapport</button></div>
  <div className="review-overview"><div className="review-photo">{photo?<img src={photo.preview} alt="Photo originale évaluée"/>:<div className="review-empty"><span>◎</span><h3>Un autre regard sur vos images.</h3><p>Ouvrez une photo, ou reprenez celle du module Watermark.</p><button className="secondary" disabled={!!busy} onClick={()=>pick()}>Choisir une photo JPEG</button></div>}</div><div className="global-card"><span className="eyebrow">NOTE GLOBALE PONDÉRÉE</span><div className="global-score" aria-live="polite">{score===null?'—':score.toFixed(1)}<small>/10</small></div><p>{assessment?.summary||'La note globale sera calculée à partir des six notes et de vos pondérations.'}</p><div className="score-formula">Σ (note × poids) ÷ Σ poids</div><small className="evaluation-meta">{assessment?`Évaluation par ${assessment.model} · ${new Date(assessment.analyzedAt).toLocaleString('fr-FR')}`:'Analyse locale avec votre modèle vision'}</small></div></div>
  {(error||sharedError||active?.reviewError)&&<div role="alert" className="message error">{error||sharedError||active?.reviewError}</div>}{notice&&<div role="status" className="message">{notice}</div>}
  {assessment&&assessment.rubricVersion!==3&&<div className="message">Ancienne grille : réévaluez cette photo pour obtenir une critique étayée et contrôlée.</div>}
  {assessment?.measurements&&<div className="measured-exposure"><strong>Mesures locales des hautes lumières</strong><span>{assessment.measurements.whitePercent} % de pixels presque blancs · {assessment.measurements.nearWhitePercent} % très clairs · luminance moyenne {assessment.measurements.meanLuminance}/255</span><small>Mesuré sur l’image décodée réduite en sRGB. Un fond blanc ou des reflets peuvent être légitimes ; ces mesures ne suffisent pas à conclure à une surexposition.</small></div>}
  <div className="criteria-heading"><h3>Les six critères</h3><span>{assessment?.audited?'Critique contrôlée en deux passes · ':''}0 = très faible · 5 = moyen · 9 = exceptionnel</span></div><div className="criteria-grid">{criteria.map(({key,label},index)=><article key={key} className="criterion-card" data-criterion={key}><div className="criterion-top"><span className="criterion-number">0{index+1}</span><h3>{label}</h3><strong>{assessment?assessment[key].score.toFixed(1):'—'}<small>/10</small></strong></div><div className="criterion-bar"><div style={{width:assessment?`${assessment[key].score*10}%`:'0%'}}/></div><p>{assessment?.[key].reason||'La justification apparaîtra après l’évaluation.'}</p>{assessment?.[key].evidence&&<details className="criterion-evidence"><summary>Observations, défauts et incertitudes</summary><dl><dt>Observations</dt><dd>{assessment[key].evidence}</dd><dt>Défauts constatés</dt><dd>{assessment[key].defects}</dd><dt>Incertitudes</dt><dd>{assessment[key].uncertainty}</dd></dl></details>}<span className="criterion-weight">Poids {weights[key]} · {totalWeight?(weights[key]/totalWeight*100).toFixed(1):'0'} % de la note globale</span></article>)}</div>
  {assessment&&<div className="review-bottom"><article><h3>Pour aller plus loin</h3><p>{assessment.improvement}</p></article><article><h3>Ce que l’analyse peut apprécier</h3><p>{assessment.limitations}</p></article></div>}<p className="review-footnote">La critique est une appréciation du modèle. La mise au point est évaluée sur un aperçu et un détail central ; l’originalité et l’impact esthétique restent subjectifs.</p>
  </div>
 </div>;
}
